"""add images json field

Revision ID: 26c24ee48479
Revises: b867a6b4c74c
Create Date: 2026-04-21 18:00:06.236466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26c24ee48479'
down_revision = 'b867a6b4c74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('images', sa.JSON(), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.drop_column('images')

    # ### end Alembic commands ###
