"""fix chat cascade

Revision ID: 336559856cf7
Revises: 4c8fcaf5c941
Create Date: 2026-04-21 21:15:15.200460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336559856cf7'
down_revision = '4c8fcaf5c941'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('message_chat_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'chat', ['chat_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_chat_id_fkey'), 'chat', ['chat_id'], ['id'])
        batch_op.alter_column('chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
