"""fix user and property models

Revision ID: 4f8ba02e583b
Revises: b9dcc7a5695e
Create Date: 2026-04-17 12:20:34.528014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8ba02e583b'
down_revision = 'b9dcc7a5695e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('featured_amount', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_paid', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('subscription_plan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('subscription_expiry', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('subscription_expiry')
        batch_op.drop_column('subscription_plan')
        batch_op.drop_column('verification_paid')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('featured_amount')
        batch_op.drop_column('featured_paid')

    # ### end Alembic commands ###
