"""add favorites

Revision ID: 52c943d9979a
Revises: 4a827a3f44c9
Create Date: 2026-05-01 13:24:58.119205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c943d9979a'
down_revision = '4a827a3f44c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_unique_constraint('unique_user_property_favorite', ['user_id', 'property_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_property_favorite', type_='unique')
        batch_op.alter_column('property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
