"""add slug to property

Revision ID: 573ba3e35072
Revises: 52c943d9979a
Create Date: 2026-05-08 19:16:28.532231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573ba3e35072'
down_revision = '52c943d9979a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_property_slug'), ['slug'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_property_slug'))
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
