"""update user verification system

Revision ID: 577208c3e6b7
Revises: 336559856cf7
Create Date: 2026-04-24 10:41:49.172224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '577208c3e6b7'
down_revision = '336559856cf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('featured_amount')
        batch_op.drop_column('featured_paid')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_doc', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('verification_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('verified_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('verification_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.drop_column('is_verified')
        batch_op.drop_column('verification_paid')
        batch_op.drop_column('id_document')
        batch_op.drop_column('is_premium')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_premium', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('id_document', sa.VARCHAR(length=300), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('verification_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('verification_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('subscription_plan',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('verified_at')
        batch_op.drop_column('verification_note')
        batch_op.drop_column('verification_doc')

    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured_paid', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('featured_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
