"""update property model

Revision ID: 6c610799badc
Revises: 26c24ee48479
Create Date: 2026-04-21 18:41:14.646731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c610799badc'
down_revision = '26c24ee48479'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_history', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('property_history_property_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'property', ['property_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('property_history_property_id_fkey'), 'property', ['property_id'], ['id'])

    # ### end Alembic commands ###
