"""add bedrooms

Revision ID: 7a40e3692afc
Revises: bf12c8eedf00
Create Date: 2026-04-19 16:46:15.226434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a40e3692afc'
down_revision = 'bf12c8eedf00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bedrooms', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('bedrooms')

    # ### end Alembic commands ###
