"""add approved field

Revision ID: 90efc00b5a86
Revises: 2dfeb556c091
Create Date: 2026-04-16 20:55:29.026290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90efc00b5a86'
down_revision = '2dfeb556c091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.drop_column('approved')

    # ### end Alembic commands ###
