"""add verification system

Revision ID: b9dcc7a5695e
Revises: d7707cb84645
Create Date: 2026-04-17 11:31:35.859034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9dcc7a5695e'
down_revision = 'd7707cb84645'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('id_document', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.String(length=200), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.alter_column('password',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('experience')
        batch_op.drop_column('location')
        batch_op.drop_column('profile_image')
        batch_op.drop_column('id_document')
        batch_op.drop_column('verification_status')
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
